### ISSUE TITLE
add arrow between the two

### ISSUE THREAD

**Issue by edireson** [laughing-waffles/transfervox#4]
![Screen Shot 2022-06-16 at 11 49 56 AM](https://user-images.githubusercontent.com/368674/174124317-4b6bf9b5-a370-4f43-a9cd-255ea95416c3.png)

just to make it super clear you can go from *this* to *that*

**Comment by judsonlmoore** [comment]
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/52468936/193917384-09374612-2b0e-4da6-a688-5d8c3366b9ba.png">
Done
